---
title: "Final Report"
author: "Eric Rios, Emma Wang, Pragya Raghuvanshi, Lorna Aine"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Abstract (A few sentences describing the purpose of the analysis, the data, and key results)

Our main research purpose the analysis is to explore the effect of most of the musical aspects on its popularity and explicitness. In other words, we want to find out what causes the song to go viral and what are the variables that cause the song to be flagged as explicit. The analysis may help music producers get a better sense at both marketing and social aspects. The dataset used is from a larger spotify dataset with variables: popularity, explicitness, danceability, energy, speechiness, loudness, acousticness, instrumentalness, and tempo. The key results show that [add RQ1]. It also demonstrates that danceability, energy, speechiness, and tempo are all able to predict explicitness to some extent, while if the music producers do not want the song to be flagged as explicit, they might want to make dancebility and energy aspect less evident.


#Introduction: Provide more background on the data and research questions. Be sure to cite the data
and background information appropriately (APA style is fine)

The data set used in this research is a subset of a larger [spotify dataset](https://www.kaggle.com/datasets/yamaerenay/spotify-dataset-19212020-600k-tracks) that contains 104,767 tracks and 23 variables for songs between 2010 and 2019. Our focus for this research is to infer which musical features are best associated to the popularity of songs in the 2010s and to what extent can another musical set of features predict if a song, regardless of year, will be explicit or not. In this statistical plan, we shall explore two types of models to answer the research questions, and elaborate how variables were selected and suggest potential remedies for any arising challenges.

[add RQ1]


Given that the second research question aims to predict whether a song is explicit or not based on its danceability, energy, speechiness, and tempo, the second RQ is thus formulated as 
"To what extent can the musicality of a song predict whether a song will be explicit or non-explicit?"
The goal is to predict the probability and use a 0.5 threshold to categorize whether a song is explicit or not, using a binary response variable based on continuous variables danceability, energy, speechiness, and tempo. Additionally, we shall treat the response variable as a factor (explicitness = 1, non-explicitness = 0). To accomplish this, we employed multiple logistic regression. 


# Methods
Describe the process you used to conduct analysis. This includes EDA and any relevant
data cleaning information (e.g., did you exclude missing values? If so, how many? Did you collapse categories for any variables?) Then describe the models you fit, and any changes you made to improve model fit (e.g., did you exclude any influential points? Did you do have to address multicollinearity issues? Did you transform any variables?). Also describe model diagnostics. The organization of this section may depend on your particular dataset/analysis, but you may want to break it into subsections such as “Data,” “Models,” and “Model assessment.” Note that you do not present any results in this section.

[Add RQ1]

For the Second Research Question, we chose to use logistic regression to model the relationship between explicitness and its predictors. This type of regression model is used for variables that have only two values from which to choose. In this case, a song is either explicit or non-explicit, two categories. The second step was to divide our data into `train set` and `test set`, where the former and latter are comprised of songs from 2010-2017 and 2018-19 respectively. Then the process concludes with three final steps, assessing the significance of the predictors in the model as well as their insights, checking potential multicollinearity by VIF scores, and evaluating the model's accuracy. For the first, the coefficients of our predictors indicate the odds ratio that our song may be explicit as compared to inexplicit. For the second, we verify that our variables are not influencing each other too much because they are assumed to be independent of each other. For the third, the model generated from the train set is used to predict the likelihood of a song being explicit or non-explicit in the test set, which is the final step in logistic regression (cite). We then gauge the effectiveness of our model by observing the general accuracy values and the Area Under the Curve (AUC) value, another measure of how well the model is predicting the negatives and positives in a study. 

# Results
Here you should present results for all aspects of the analysis. The structure of this section should mirror the structure of the methods section. For example, you can start with a few key EDA results (e.g., a table of descriptive statistics), then present model results, then address assessment. This is the section where you will primarily refer to tables and figures. You should have at least 1 figure for each research question that illustrates a key result of the analysis.
# Conclusion
Describe the key takeaways from your analysis, limitations, and future work that can be done to advance knowledge in this area.
