---
title: "Part 2 - Statistical Analysis Plan"
author: "Eric Rios, Emma Wang, Pragya Raghuvanshi, Lorna Aine"
date: "2022-11-02"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Part 2: Statistical Analysis Plan

In part 2, you will produce a statistical analysis plan. The plan should be at most 2 pages, produced in R
Markdown, and include the following:
2



• Overview: Briefly describe the dataset and research questions.

The data set used in this research is a subset of a larger [spotify dataset](https://www.kaggle.com/datasets/yamaerenay/spotify-dataset-19212020-600k-tracks) that contained `r format(nrow(df), big.mark = ",")` tracks. Our final subset of the data set of interest to our research problems contains `r format(nrow(subset), big.mark = ",")` of observations/ tracks and `r ncol(subset)` of variables for songs between 2010 and 2019.
Our focus in this research is to infer which features of music are best associated to the popularity of songs and to predict if a song will be explicit or not based on these features. Our Research Questions:

-What are the musical attributes that gauged the popularity of songs in the 2010s? 
*Dependent Variable (continuous) = popularity;*
*Independent Variables = acousticness, danceability, energy, instrumentation, tempo, loudness, and speechiness* 
 
-To what extent can the musicality of a song predict whether a song will be explicit or non-explicit? 
*Dependent Variable (categorical) = Explicitness;*
*Independent Variables = danceability, energy, speechiness, and tempo* 



• Models: Describe the type of model you will use for each research question. Justify your selections.






In our Research Question 1, our goal is to infer the musical attributes that are most important in guaging the popularity of the song in the 2010s decade. The analysis will be performed with the predictor variables- acousticness, danceability, energy, instrumentation,tempo, loudness, and speechiness and the response variable as popularity. 

Dependent Variable : Our response variable of interest is *popularity* which is a continuous variable that is based on how many times a track has been played.

Independent Variable: The independent predictor variables chosen are based on domain knowledge. The independent variables are *acousticness*, *danceability*, *energy*, *instrumentation*, *tempo*, *loudness*, and *speechiness*. These are musical attributes of the tracks that can most contribute to popularity, our response variable. 

Multiple Linear Regression: Multiple linear regression (MLR) is a statistical technique that uses several independent explanatory variables to predict the outcome of a response variable. The goal of this analysis is to model the linear relationship between the independent variables and the dependent variables.

Multiple Linear Regression will be conducted for RQ1 due to the following reasons: 

*1. A dependent variable is rarely explained by only one variable. Here too, multiple musical attributes (predictor variables) are taken in consideration for guaging the popularity(dependent variable), so MLR is performed on the same. 
*2. The nature of the response variable is continuous making it best fit for performing Linear Regression.
*3. From the Exploratory Data Analysis we can observe that there is some relation between the variables with the outcome, which we will probe further in the MLR model analysis. 







In research question 2, we ask “To what extent can the musicality of a song predict whether a song will be explicit or non-explicit? (musicality = danceability, energy, speechiness, and tempo)“, Multiple Logistic Regression will be conducted for following reasons:
*1. Our research question includes a response variable that is binary and categorical, namely explicitness and non-explicitness, with multiple predictors.
*2. The goal is to predict the probability that the song belongs to a particular category, namely explicitness or non-explicitness. For this, we will set the cutoff point at 0.5, where everything greater than or equal to this cutoff indicates explicitness, while the rest is non-explicit.

Pre-processing: 

In order to generate the predictive probabilities, we will split our dataset into training set and test test. More specifically, our training set will consist of songs released in 2010-2017 and will contain the data to fit our model, while our test-set, the one for which we will generate predictive probabilities, will be made up of songs between 2018 and 2019. Additionally, we will set the response variable as a factor (explicitness = 1, non-explicitness = 0).


Model-fitting

After the regression model is fit, we will verify if our model's predictors exhibit multi-collinearity. To do this, we will perform a Variable Inflation Factor (VIF) test to see if there is a score higher than 5.0, a sign of strong correlation between predictors. If there is at least one predictor with a score higher than 5, it suggests potential multi-collinearity, and we may consider refitting the regression model without said predictor.

At this stage, we will also look at the binned residuals plot, to verify that the data falls within the band of a 95% confidence interval. If the majority of the points are not contained within those bands, a transformation may be necessary. As for the assumptions, we will asess independence, which appears to already be satisfied, given how the data was collected. Lastly, the difference between the null deviance and residual deviance will also serve as an indicator to assess the overall fit.


Evaluation:

To evaluate our result from logistic regression, we will calculate the accuracy of our predictive probabilities, plot the ROC curve with AUC value. We will then be able to know how well the model predicted the probabilities of explicitness and non-explicitness (1 vs 0) for the out-of-sample, test data (year 2018-2019). After this initial assessment, we will proceed into a k-fold cross-validation stage, where the entirety of the data, segmented into an arbitrary number of groups, will be divided into training and test sets and have a logistic regression model fitted to it at each step, until all the groups of data points have been part of both a training and test set. After the cross-validation is completed, we will finally be able to ascertain the overall success of the model's predictive accuracy, which is a metric gathered from all of the accuracies of the models fitted during the cross-validation test. 



• Variable selection: How will you perform variable selection for your models? For each research question, list any variables that you are selecting a priori to be included in your model.

For both questions, domain knowledge of musical terminology played the most important role in doing “a priori” selection for the predictors. Regarding the first question, we are investigating if the aforementioned musical attributes have an associative relationship with popularity. Popular songs, whether they are an emotional ballad or a dance track, have an assortment of features that keep the listeners engaged and interested (Leviatan, 2017). Tempo, energy and loudness command the pacing and sonic impact of the song. Speechiness, danceability, instrumentation, and acousticness pertain to the selections and progressions of chord structures, melodies, and vocal and instrumental arrangements. All of these features are regulated by their context, meaning that the genre of music governs how much of each feature is present in a track. For example, an instrumental song, like a Star Wars theme song, has a speechiness of zero, since no vocals are present (Androids, 2017). In short, we are interested in determining if the any or most of these factors exercise an influence over the popularity of songs. In addition, we will also determine which predictors will remain in the final model via backwards selection, which will further narrow down our predictors to the most essential ones. 

As for the second research question, we hypothesized that the explicitness of tracks, the presence of inappropriate language, was most swayed by the following factors. High levels of speechiness and specific tempos in songs are strong indicators. For example, rap songs are a likely candidate for explicitness for three reasons. The verses are composed in a spoken word format over a series of 8 or 16 bars (Edwords), and they can sometimes follow a specific tempo (Burchell, 2019), and songs in general, beyond this genre, have become more explicit over time, especially sexual in nature (Tayag, 2017). For energy and danceability, our last two predictors, we hypothesize, based on the current songs charting on the Hot 100 (Billboard, 2022), that they collude with explicitness because an energetic song could be more likely to feature explicit language than a less energetic song. For these reasons, we choose these variables as predictors for explicitness.


• Challenges: How do you plan to address the challenges you presented in part 1?

In part I, we proposed one limitation that our “explicitness" as a dependent variable does not have even distribution over years. Specifically, songs from the 2017-19 range present more explicitness than non-explicitness, meaning that training for explicit songs could be limited by fewer explicit data points found in the older half of the 10s decade. Thus, one way to decrease the drawback is that when logistic regression is conducted, our train set will only include years from 2010-2017, so that the training process would have less unequal proportion of explicit and inexplicit songs. Another challenge is how the same artists can monopolize the most popular songs categories. In our case, that is beyond the scope of our study, given that we care about the musical attributes that make the songs popular, not the celebrities singing them; however, it is a great avenue for exploration, for which suggestions will be recommended at the conclusion of this formal study. As for the last challenge, it is the discovery of multicollinearity between our predictors. Our solution is to run Variable Inflation Factor (VIF) tests and remove variables with VIFs higher than 10.



\newpage

# Bibliography

Androids (2017, October 13). An Idiot’s Guide to EDM Genres. Retrieved October 20, 2022, from https://www.complex.com/music/an-idiots-guide-to-edm-genres/

Billboard. (2022, October 29). Billboard Hot 100. Billboard Media. Retrieved November 3, 2022. https://www.billboard.com/charts/hot-100/2022-10-29/

Burchell, C. (2019, May 27). 10 Tips for Making Your First Trap Beat. Inverse. Retrieved October 20, 2022, from https://flypaper.soundfly.com/produce/10-tips-for-making-your-first-trap-beat/#

Edwords, E. (n.d.). Rap Song Structure Is TOO Important To Ignore. Retrieved October 20, 2022, from https://rhymemakers.com/rap-song-structure/

Leviatan, Y. (2017, July 27). Making Music: The 6 Stages of Music Production. Waves. Retrieved October 20, 2022, from https://www.waves.com/six-stages-of-music-production

Spotify (2022). Spotify Web API Reference | Spotify for Developers. https://developer.spotify.com/documentation/web-api/reference/#/operations/get-audio-features

Tayag, Y. (2017, May 17). Expert on Male Psychology Explains How Pop Got Sexually Explicit. Retrieved October 20, 2022, from https://www.inverse.com/article/31842-pop-music-sexually-explicit-lyrics-rap-hip-hop

Yamac. (2016). Spotify Dataset 1921-2020, 600k+ Tracks. Spotify. Retrieved October 3, 2022, from https://www.kaggle.com/datasets/yamaerenay/spotify-dataset-19212020-600k-tracks
